# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysGIumU4OuJfCFPZiQcWnhUoBHFk6b9x
"""

def tashxis (belgi):
  if   belgi == "istima":
    return "Parasetamol iching"
  elif belgi == "bosh og'riq":
    return "Trimol iching"
  elif belgi =="Tish og'riq":
    return "Quepen iching"
  elif belgi == "Artrit":
    return "voltaren maz"
  elif belgi== "Gastrit":
    return "Omeprazol"
  elif belgi== "nerviniy":
    return "magniy b6"
  elif belgi== "ko'z og'riq":
    return "tetroksin"
  elif belgi=="Uyqusizlik":
    return "ketotefen"
  else:
    return "Shifokorga murojaat qiling"
belgi=input ("Kasallik belgisini kiriting")
natija=tashxis (belgi)
print(natija)

def kutubxona (belgi):
   if belgi=="Sayohatnoma":
    return "50 ming "
   elif belgi=="Imomning qizi":
    return "100 ming"
   elif belgi=="Dardisar":
    return "45 ming"
   else:
    return "Mutaxasisga murojat qiling"
belgi=input ("Kitob nomini kiriting")
natija=kutubxona (belgi)
print(natija)